#PGSQL
PG_HOST=localhost
PG_PORT=5432
PG_DATABASE=KazalisteDb
PG_USER=postgres
PG_PASSWORD=secret

#HIKARI Connection pool
POOL_MAXIMUM_POOL_SIZE=10
POOL_MINIMUM_IDLE=2
POOL_CONNECTION_TIMEOUT=30000
POOL_IDLE_TIMEOUT=600000
POOL_MAX_LIFETIME=1800000